### ISSUE TITLE
DB locked after reboot

### ISSUE THREAD

**Issue by prescott66** [manjaro/pamac#25] opened 2015-01-15 07:32 UTC
After every reboot i get pacman db locked, so i must everytime manually remove /var/lib/pacman/db.lck

**Comment by manjaro** [comment] 2015-01-17 10:30
Seems to be related to #5 and #10. Do you use pure Arch or Manjaro?

**Comment by prescott66** [comment] 2015-01-17 12:35
I am using antergos 64bit.so i it is pure arch

**Comment by guinux** [comment] 2015-01-17 15:15
I can't reproduce it, does it happen also with Manjaro ?

**Comment by manjaro** [comment] 2015-01-17 16:18
Not on my end. Maybe network related. The user uses wifi and posted a [url=https://github.com/aarnt/octopi/issues/63]similar issue[/url] to the octopi project.

**Comment by prescott66** [comment] 2015-01-17 16:21
no. with octopi i dont get db lock problem, never.

**Comment by manjaro** [comment] 2015-01-17 16:25
Anyway, there it was fixed by checking for [internet connection](https://github.com/aarnt/octopi/commit/40f4f1afcd7a215a29cf24632ad645873f3d2d02). We might add this also to **pamac-daemon**.

**Comment by guinux** [comment] 2015-01-19 19:12
Pamac-tray refresh databases and check for updates at startup so it's normal if the db lock file is present during this process. Do you let pamac to have the time to do this before trying to access the databases ?

**Comment by manjaro** [comment] 2015-01-19 21:15
@guinux: please download our latest [0.9.0-dev build](http://sourceforge.net/projects/manjarotest/files/0.9.0/xfce-minimal/0.9.0-dev/) and see for yourself. On each bootup you have a looked db. Last tested with 2015-01-19 + pamac 2.1-8 (54591d4bc939e6d204fe0c9d4de3bb495dcd17c4)

**Comment by manjaro** [comment] 2015-01-19 23:16
@guinux [0.9.0-pre1](http://sourceforge.net/projects/manjarotest/files/0.9.0/xfce/0.9.0-pre1/) seems to be fine on the other hand ...

**Comment by guinux** [comment] 2015-01-20 07:23
:D

2015-01-20 0:16 GMT+01:00 Manjaro Linux <notifications@github.com>:

**Comment by manjaro** [comment] 2015-01-20 08:00
Well, I can't pinpoint the issue. Something is there locking the database and it is pamac related ...

**Comment by manjaro** [comment] 2015-01-20 08:03
@guinux: install 0.9.0-dev on a virtual machine. If you boot it up you'll see db.lck and pamac service failing. If you open pamac-updater or manager you get the notice that db is locked. Remove the lock and reboot. Well you get the lock again and daemon failing ... Maybe an issue with manjaro-tools or something else. At least it is within the daemon.

**Closed** 2015-01-21 16:07 UTC

**Comment by guinux** [comment] 2015-01-21 16:08
I tried something to fix it, can you test and report ?

**Comment by manjaro** [comment] 2015-01-22 00:08
Will do that with 0.8.12-rc1 and next 0.9.0-dev ...

**Comment by prescott66** [comment] 2015-03-26 21:22
i get this issue some times in last wekk on antergos. i get updates only after removing db.lck

**Comment by amallick10** [comment] 2015-03-29 19:50
i have a same issue on antergos 64 (openbox), not getting notification until i manually remove db.lck

**Comment by philmmanjaro** [comment] 2015-03-29 19:52
Is this issue still there with v2.2.2?

**Comment by prescott66** [comment] 2015-03-30 07:07
Tested morning.looks ok but notification and red status icon was not shown immediately.only after my trigger-check for updates

**Comment by amallick10** [comment] 2015-03-30 12:38
Yes, so far so good, working fine i.e; received the update notification at startup thanks

**Comment by philmmanjaro** [comment] 2015-03-30 16:24
This is normal. Pamac waits for one hour or get updated due network changes.

**Comment by prescott66** [comment] 2015-04-08 19:45
sorry guys but i get randomly db locked after reboot....i dont know where can be problem. using latest Pamac...how can i debug my system/pacman/pamac? i want to really help to fix this strange boring issue.

**Comment by MagnusOxlund** [comment] 2016-02-12 17:31
I had this issue recently, about two days ago. 

I was in the process of updating some input related packages when rebooting, and I was unfortunate enough to not be able to use my keyboard after the reboot.
