### ISSUE TITLE
Tray Icon needs some extra love in E desktop environment

### ISSUE THREAD

**Issue by NuLogicSystems** [manjaro/pamac#164] opened 2016-09-04 11:45 UTC
I know this probably not an issue anywhere but on Enlightenment, but both notifier .desktop files have the same internal name (update notifier). The problem is in startup applications only one listing shows, and it's the non appindicator one. I had to manually delete pamac-tray.desktop so that I could choose pamac-tray-appindicator.desktop in startup applications.

**Comment by philmmanjaro** [comment] 2016-09-04 14:51
It is only needed for **KDE**. On Enlightenment you don't have to install it.

**Comment by NuLogicSystems** [comment] 2016-09-04 15:11
That is wrong.
Plasma  (KDE) still supports xembed through the sni-proxy that is now built into the system tray,
Enlightenement ONLY supports appindicators (SNI) in it's system tray.
I am now working on Enlightenment and up until this appindicator progress was stuck using Octopi-notifier-qt5, the package manager integration module, or stanalonetray (which is not ideal). So the more applications that support appindicators the better.

**Comment by philmmanjaro** [comment] 2016-09-04 15:34
Please check the **tray** once more: [desktop file](https://github.com/manjaro/pamac/blob/master/data/applications/pamac-tray-appindicator.desktop). We only show it in KDE and not in other DEs like E19. As we currently only designed it for KDE in mind. If E19 is also needed we can add it there also. Please edit the file as needed and request for merge.

**Comment by NuLogicSystems** [comment] 2016-09-04 15:40
Philip, I have it installed and running in E 0.21. The one in the pamac package has never worked this one does. In E you have to select what things are to autostart, E does not support autostart from the xdg directory it only reads what is there. Once I deleted the pamac-tray.desktop file I was able to load the pamac-tray-appindicator.desktop file in Menu >  Settings > All > Apps > Startup Applications.
http://www.enlightenment.org/ss/e-57cc405c563c26.27586824.jpg

**Comment by NuLogicSystems** [comment] 2016-09-04 16:04
Ah, I see what is happening with the desktop files now. I had to look at both of them. 

Yes please add enlightenement to both desktop files so the the appindicator one is the only one to be listed in E. (NotShowIn and  OnlyShowIn respectfully).
Thanks

PS. I do apologize for not noticing that sooner.

**Comment by NuLogicSystems** [comment] 2016-09-04 16:21
However, I'm still not 100% sure this will work either since the pamac-tray-appindicator.desktop one still shows up even after I've deleted the pamac-tray.desktop file. So the questing is then does E even read the OnlyShowIn line.

**Comment by philmmanjaro** [comment] 2016-09-04 16:25
I don't know E as good as others do. I understand your issue there. However you can write a launcher for now to delete the non-working tray-desktop until **Guillaume** comes up with something else ...

**Comment by NuLogicSystems** [comment] 2016-09-04 16:27
Yes, I may just do that, or wait. I'm a patient man. ;)

At any rate great job guys, I'm really enjoying having one that works as expected. 
PS: On a side note, msm notifier works great as well.

**Comment by guinux** [comment] 2016-09-07 13:20
I think the problem is that the two desktop files have the same Name variable.
It's fixed in 71be416, tell if it works now.

**Comment by NuLogicSystems** [comment] 2016-09-07 13:43
Thanks, that should fix the issue as both should now be available (in E's list).
As soon as I get a chance I'll test this.

**Closed** 2016-09-29 15:12 UTC
