### ISSUE TITLE
pamac 4.1b1-2 "View History" no response

### ISSUE THREAD

**Issue by badbodh** [manjaro/pamac#127] opened 2016-05-15 09:41 UTC
![screenshot_2016-05-15_15-19-25](https://cloud.githubusercontent.com/assets/17335519/15273203/223dfc42-1aaf-11e6-9e98-1d418842ba20.png)

I performed a few updates (testing updates on 15th May) and install/remove (+i3-gaps, -i3-wm) and expected "View History" item to show something. It does not respond at all, not even an empty window or error message. What's missing here ?

**Comment by guinux** [comment] 2016-05-15 09:44
I know it, it's certainly because I want to merge pamac log file with pacman.log but the implementation is incomplete yet.
It will be fixed in beta2.

**Comment by philmmanjaro** [comment] 2016-05-15 09:58
Currently I can't reproduce your issue. However, as @guinux already mentioned, it shows only things you did with **pamac**.

![history](https://cloud.githubusercontent.com/assets/5050022/15273299/489c1952-1a94-11e6-8577-411a550fc282.png)

**Comment by badbodh** [comment] 2016-05-15 11:48
that's why i did today's update and an install/remove with pamac as mentioned above. History window doesn't show up at all.
These are pacman.log entries that were actually done using pamac
`[2016-05-15 14:24] [PAMAC] synchronizing package lists`
`[2016-05-15 14:24] [PAMAC] synchronizing package lists`
`[2016-05-15 14:25] [PAMAC] synchronizing package lists`
`[2016-05-15 15:04] [PAMAC] synchronizing package lists`
`[2016-05-15 15:08] [ALPM] transaction started`
`[2016-05-15 15:08] [ALPM] upgraded octave (4.0.1-4 -> 4.0.2-1)`
`[2016-05-15 15:08] [ALPM] upgraded rest (0.7.93-1 -> 0.8.0-1)`
`[2016-05-15 15:08] [ALPM] upgraded thunderbird (45.0-1 -> 45.1.0-1)`
`[2016-05-15 15:08] [ALPM] upgraded thunderbird-i18n-en-us (45.0-1 -> 45.1.0-1)`
`[2016-05-15 15:08] [ALPM] transaction completed`
`[2016-05-15 15:08] [ALPM] running 'gtk-update-icon-cache.hook'...`
`[2016-05-15 15:08] [ALPM] running 'texinfo-install.hook'...`
`[2016-05-15 15:08] [ALPM] running 'update-desktop-database.hook'...`
`[2016-05-15 15:11] [PAMAC] synchronizing package lists[2016-05-15 15:16] [ALPM] transaction started`
`[2016-05-15 15:16] [ALPM] removed i3-wm (4.12-1)`
`[2016-05-15 15:16] [ALPM] installed i3-gaps (4.12.r5.rg3764415-1)`
`[2016-05-15 15:16] [ALPM] transaction completed`
`[2016-05-15 15:16] [ALPM] running 'update-desktop-database.hook'...`
`[2016-05-15 15:44] [ALPM] transaction started`
`[2016-05-15 15:44] [ALPM] installed artwork-i3 (20160510-1)`
`[2016-05-15 15:44] [ALPM] installed i3-help (20160308-2)`
`[2016-05-15 15:44] [ALPM] transaction completed`

**Comment by badbodh** [comment] 2016-05-15 11:50
Last few lines from my xsession-errors when i started pamac, more or less.
`[1342:1374:0515/171347:ERROR:connection_factory_impl.cc(367)] Failed to connect to MCS endpoint with error -202
[1342:1372:0515/171350:ERROR:zygote_host_impl_linux.cc(162)] Failed to adjust OOM score of renderer with pid 1501: Permission denied
[1342:1372:0515/171350:ERROR:zygote_host_impl_linux.cc(162)] Failed to adjust OOM score of renderer with pid 1509: Permission denied
[1342:1372:0515/171351:ERROR:zygote_host_impl_linux.cc(162)] Failed to adjust OOM score of renderer with pid 1606: Permission denied
[1342:1372:0515/171402:ERROR:zygote_host_impl_linux.cc(162)] Failed to adjust OOM score of renderer with pid 1642: Permission denied
[1342:1372:0515/171918:ERROR:zygote_host_impl_linux.cc(162)] Failed to adjust OOM score of renderer with pid 2214: Permission denied
[1342:1372:0515/171922:ERROR:zygote_host_impl_linux.cc(162)] Failed to adjust OOM score of renderer with pid 2223: Permission denied
[1342:1372:0515/171924:ERROR:zygote_host_impl_linux.cc(162)] Failed to adjust OOM score of renderer with pid 2235: Permission denied
File '/var/log/pamac.log' doesn't exist.`

**Comment by guinux** [comment] 2016-05-15 12:01
Pamac now writes it's log in pacman.log but I forgot to update history dialog which still try to show logs from pamac.log. I will fix it with my next push.

**Comment by philmmanjaro** [comment] 2016-05-16 11:45
This is fixed with **pamac 4.1b1-3**

**Closed by philmmanjaro** 2016-05-16 11:45 UTC
