### ISSUE TITLE
false update notification

### ISSUE THREAD

**Issue by oberon2007** [manjaro/pamac#297] opened 2017-09-16 22:50 UTC
![update](https://user-images.githubusercontent.com/11800714/30516520-061f78d2-9b42-11e7-9add-d5840e492268.png)

As you can see in the tray in the screenshot, "updates available" icon is used although system (including AUR) is up-to-date.
Using latest **v6.0.1**

**Comment by oberon2007** [comment] 2017-09-16 22:53
After killing and restarting **pamac-tray** display is correct.

**Comment by guinux** [comment] 2017-09-17 07:10
Does it occur after installing updates or not ?

**Comment by kewlfft** [comment] 2017-09-17 07:25
Same here after installing updates the icon was still showing 'updates available', after restarting pamac-tray it appeared as 'updated'

**Comment by philmmanjaro** [comment] 2017-09-17 07:40
Does it occur after updating **pamac** itself? I assume only when **pamac-tray** get replaced with a new version, the old display stays as the tray never got reloaded until you reload or kill the process manually.

**Comment by elishl** [comment] 2017-09-17 08:04
Philm is right.
I've noticed this happening only when updating **pamac itself**.

**Comment by philmmanjaro** [comment] 2017-09-17 08:05
It is a known bug since **v5** as we joined **tray** with **pamac** itself. We have to see on how to fix that, if possible.

**Comment by kewlfft** [comment] 2017-09-17 08:38
yes correct it happens when pamac itself updates, not a big issue

**Comment by guinux** [comment] 2017-09-20 16:13
I can't reproduce it when updating pamac v5.1.1 to v6.0.1 but I think it is be related to #298.
It doesn't seem to occur if you don't "play" with branches.

**Comment by guinux** [comment] 2017-09-21 13:43
Should be fixed with 34130bb

**Closed** 2017-09-21 19:22 UTC
