### ISSUE TITLE
[Request] Add an option to revert to old tabbed layout

### ISSUE THREAD

**Issue by gabrc52** [manjaro/pamac#355] opened 2017-10-25 12:52 UTC
I like the old tabbed layout better. It requires less clicks, and is more straightforward. What are the advantages of this new sidebar layout? Can an option be added to use tabs?

**Comment by tttom64** [comment] 2017-11-01 04:18
Just so you know, a fork of version 5.x.x was made and actively maintained, with the old layout: https://github.com/cromnix/pamac-classic

**Comment by tabepic** [comment] 2017-11-01 04:29
I agree with @gabrc52 that there should be an option to change to the "old" interface, however I think that it may be too much to maintain (especially because pamac is becoming more of an app store rather than a pacman frontend).

In the meantime (or if the options are never added), there is pamac-classic (as @tttom64 said).

On a side note, it would be interesting to see how many people prefer the old vs the new interface.

**Comment by Huluti** [comment] 2017-12-09 18:17
Duplicate of #302.

**Closed by Huluti** 2017-12-09 18:17 UTC
