### ISSUE TITLE
Hide AUR search if disabled in settings

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/pamac#57] opened 2015-07-15 20:15 UTC
Currently if you disable AUR in settings it turns of the search but don't hide it. Therefor it is possible to re-enable it (and it works) but settings shows still disabled AUR support.

![pamac-aur](https://cloud.githubusercontent.com/assets/5050022/8709010/c8a4c058-2b3f-11e5-9518-438d2f76f447.png)

**Comment by guinux** [comment] 2015-07-16 12:40
Yes it is intentional, I created the setting mainly for the updater, but I can easily hide the AUR checkbox in the manager if you think it would be more clear and consistent.

**Comment by philmmanjaro** [comment] 2015-07-16 18:07
If you disable AUR-Support I'd suggest to hide the AUR search also. Else the user might think that option has no function. Sure, updater would not use AUR but you can still search for it. For me it was not clear that you can disable the updater but still be able to search and install AUR packages. Let others also comment on this one, before we change anything.

**Comment by ringo32** [comment] 2015-07-16 22:58
Also if you want to Enable standard Aur and aur package need update... atleast icon need to be another color as octopi does.  but i do think as Pamac-updater should not auto-update aur packages in this case it do, i have standard out :)

Also since you got settings you can setup standard dat pamac show aur  like octopi , aur only... so nothing from Repo!, if you like mixed like now you can choose this way , to keep choice up. Personal i dont see many wrong, only mayby dont mix repo & aur stuf in one list.. good is to have option 
aur-update out the updater only notifications just note by an icon upfront to update aur.....

But is a yes or no, but Aur feature is nice in a package manager but hiding it, i dont think personal community based would like to have... only thing is mayby  update notifier on pamac-tray, another color. but no aur updates standard, those things you have to set it up . personal idea*
Also packagelist not mix with the repo-list as example , but is not consistent on libreoffice does it,
http://i.imgur.com/rcGWPgJ.png

but not if you do search for xfce4 but do search manjaro , it does a mix...i would give full own page, mayby locals.. just give a update menu link in the choice if aur need update you update direct from pamac-manager , not from pamac-tray..

just my thoughts... personal hate that hiding away.. because its a feature nice to have :)
and i dont think that users that using pamac as there thing will respect it, more people use offcourse yaourt directly offcourse...with some options and documentation things wil do.

**Comment by ringo32** [comment] 2015-07-16 23:05
currently Philm picture above i dont experience as a bug.. i switch that out because i dont want that pamac say there is a update, its anoying :) sure if i go to aur i switch that button on, for me is it fine... i place it standard off....is like octopi, you go to aur or not ... only octopi notify aur packages only... actually is not a bug in my experience.. function of the aur in settings is clear enough also for me... in this configuration... but if i want to search in aur, you dont want to open settings constandly , because you need to enter your password, that is also a bug in somepoint.

**Comment by philmmanjaro** [comment] 2015-07-17 05:04
@guinux: what happens if needed dependencies are missing, i.e. build tools to compile packages. Is 'AUR Support' disabled then? Do we have a check for that?

**Comment by ringo32** [comment] 2015-07-17 06:49
its only Pamac do mix Aur-repo and Manjaro-repo , question on my side is: is it not better to seporate it ?

**Comment by alexandruianu** [comment] 2015-07-17 12:29
We should hide the setting if AUR is disabled. Installed AUR packages are shown anyway when searching, so it won't be an issue.

**Comment by korrode** [comment] 2015-07-17 12:31
>We should hide the setting if AUR is disabled. Installed AUR packages are shown anyway when searching, so it won't be an issue.

Agreed.

**Comment by guinux** [comment] 2015-07-17 13:52
Ok I will fix when I'm back at home.

**Comment by guinux** [comment] 2015-07-17 14:14
@philmmanjaro: missing deps are handle by yaourt when building packages. There is no check that the base-devel group is installed but add it as a dep of our yaourt package could fix it.

**Comment by philmmanjaro** [comment] 2015-07-17 17:52
@guinux: please add a check if yaourt is installed. Else disable AUR support by default. We will discuss what we should do about base-devel group.

**Comment by korrode** [comment] 2015-07-17 22:55
Consider perhaps two settings in the preferences, one for if the updater is going to use AUR and one for if the manager is going to search AUR.

https://forum.manjaro.org/index.php?topic=24336.msg210834#msg210834

**Comment by ringo32** [comment] 2015-07-18 05:06
yeah those two setting would be fine i gues. Also make Aur packages seporated from list, so when do a aur search, no Repo packages from list.. Personal it makes no sence you mix repo's, and even you use repo's that isn't Manjaro. Just a option to hide the aur search button or not.  But on the topic 'hiding'  would not be fine there is a base line you cant also hide things away because aur is just a feature but in current form it makes less sence because you use it as your own repo. thats not ok i think personal. and for the updating from pamac-tray option is fine, even if you switch it on, it should also a seporate option on right click on pamac-tray button that stands Update Aur packages.

Also sometimes packages goes away from repo and goes to aur from some reason and users if its enabled aur packages to update, aur should also have its own color also.

**Comment by philmmanjaro** [comment] 2015-07-18 07:23
Well, the basic idea was to integrate AUR seamlessly. In tab package source we only list our repositories there. If possible a group **AUR** might fit there. In our list we have already a separation as you can clearly read **AUR** there. Packages not found in our binary repositories or **AUR** are listed as **local**.

Settings is mostly used for updater. We can add an option to disable AUR search additionally. However, if we disable AUR support (which means we turn off updating AUR packages) currently users can still install AUR packages, as AUR search is visible.

The pressing enter thing in **yaourt** can be changed back as **pamac** support editing in its console.

For me, we need a check if **yaourt** is installed at all, if not, to **disable AUR support** completely. The other option with visibility of **AUR search** we are discussing right now. Hope everybody is on the same boat here ...

**Comment by ringo32** [comment] 2015-07-18 08:02
just confuse about 'hiding aur' on my side :p sorry for that.. but if yaourt not  is installed, it should not show up as option in pamac. Personal idea is just if you seamless integrate aur, and it show up your own repo stuf, and its standard enabled for now. people does not watch if its from aur or stuff... is just the line aur tells about the warning. we should atleast respect that line of yaourt , because u use different sources. Manjaro should guarantee only from own repo stuf and if need something from aur, just switch it on, is seamless enough en also you know what you doing because you have to switch it on...  thats why personal i like what octopi does. you see when thinks get moved to aur as example. as example, arj was in the repo once, arch put it out. so its in aur. in the package manager you see a aur logo 'alien'. you aware its not in the repo anymore this way.. local or aur does not tell me anything things from local means only its installed in your system anyway it does not tell its moved too aur as example. i use pamac only for tesrting purpose more not :) and i have aur put of in setting and use it when i want too use aur. Defnitly as guarantee never use external repo automatically as your own is a bad idea when you want to use it on a seamless way.. because aur is not manjaro its own repository also standard on is not wise also. thats mine point is not topic possible. nevermind *
discussion is ok, mayby i miss the boat..

**Comment by philmmanjaro** [comment] 2015-07-18 08:06
@ringo32: I see it the same. Having the support is good. Enabling it by default, well this we came to a conclusion is not the best way to go. Now we have to find a way to make supporting AUR more understandable. I always wonder why I still had the search visible even I disabled AUR. That is why this all got started. Reading this all, I hope we came to a clear understanding what is needed to be changed to make it better.

**Comment by ringo32** [comment] 2015-07-18 08:27
i have personal standard switch off, because idont want that update also :) if i start pamac-manager, it is off on my side. only enabling it when i use aur. it works fine this way here. and personal it should not hiding anyway no other package manager that support aur does not hide that aur option away , but if yaourt not there then you hide it offcouse because there isnt. And i dont know why on your side aur is visible, mine is aur just off  http://i.imgur.com/FtCjuJF.png this is after start.

**Comment by guinux** [comment] 2015-07-18 15:54
After reading all comments here and on the forum, what I want to do is:
- check if yaourt is installed, if not totally disable AUR support.
- add a warning that AUR is not part of Manjaro and could be unstable when enabling AUR support.
- add a suboption

**Comment by guinux** [comment] 2015-07-18 16:05
** made a mistake because I'm writing from my phone :( **

- add a suboption of AUR support to check for updates or not ( it should be enabled by default if AUR support is enabled for consistency with previous configurations)

What do you think about this?

**Comment by philmmanjaro** [comment] 2015-07-18 16:52
Yes, sound reasonable. Go for it ...

**Comment by korrode** [comment] 2015-07-19 06:37
Sounds great :+1:

**Comment by guinux** [comment] 2015-08-20 14:08
fixed in v2.4.0

**Closed by guinux** 2015-08-20 14:08 UTC
Labels: enhancement, question
