### ISSUE TITLE
Pamac doesn't find updates automatically

### ISSUE THREAD

**Issue by Mel34** [manjaro/pamac#331] opened 2017-10-03 14:28 UTC
Opening Pamac and pressing the Updates tab, results in a short wait and a “System is updated”.
But if you Synchronize Databases, it finds all the updates. This requires the sudo password, while the regular “check” above does not.

See: https://forum.manjaro.org/t/pamac-do-not-find-updates-automaticaly/32263

**Comment by lots0logs** [comment] 2017-10-03 14:38
I can confirm this bug. Though I'm pretty sure having or not having to enter password is unrelated. The issue is simply that updates do not show up unless you manually refresh the databases (using the option in the pamac's main menu).

**Comment by pmargeti34** [comment] 2017-10-05 20:46
Now Pamac notifies about new updates available with your patch however pamac-manager still needs "Refresh databases" to see the new update. It says "System is updated" otherwise.

**Comment by lots0logs** [comment] 2017-10-05 20:50
@guinux ^--- https://github.com/manjaro/pamac/issues/331#issuecomment-334587059 ---^

**Comment by guinux** [comment] 2017-10-06 07:21
This time I hope it's fixed ;)

**Comment by pmargeti34** [comment] 2017-10-06 11:19
It's not. Update is visible in pamac-manager but Apply doesn't work. Details outputs the following text:
`
Synchronizing package databases...
Starting full system upgrade...
`
Update isn't applied. 

Forcing 'Refresh databases' and then hitting Apply results in update being successfully applied.

**Comment by philmmanjaro** [comment] 2017-10-06 11:21
@pmargeti34: which version of **pamac** do you use? I've applied and released needed patches to **v6.0.3-3**.

**Comment by pmargeti34** [comment] 2017-10-06 11:29
[anon@loonix ~]$ LANG=c pacman -Qi pamac-aur-git 
Name            : pamac-aur-git
Version         : v6.0.3.r2.g78b8257-1
Description     : A Gtk3 frontend for libalpm - git version
Architecture    : any
URL             : https://github.com/manjaro/pamac
Licenses        : GPL3
Groups          : None
Provides        : pamac  pamac-aur
Depends On      : glib2>=2.42  json-glib  libsoup  dbus-glib  polkit  vte3>=0.38  gtk3>=3.22  libnotify  desktop-file-utils
                  pacman>=5.0  pacman<5.1  gnutls>=3.4  appstream-glib  archlinux-appstream-data  libappindicator-gtk3
Optional Deps   : polkit-gnome: needed for authentification in Cinnamon, Gnome [installed]
                  lxsession: needed for authentification in Xfce, LXDE etc.
                  pamac-dev-tray-appindicator-git: tray icon for KDE
Required By     : None
Optional For    : None
Conflicts With  : pamac  pamac-aur
Replaces        : pamac-aur
Installed Size  : 2.94 MiB
Packager        : Unknown Packager
Build Date      : Fri Oct 6 12:10:03 2017
Install Date    : Fri Oct 6 12:10:04 2017
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None

**Comment by guinux** [comment] 2017-10-06 12:36
I can't reproduce the fact that updates are not applied. Does anyone else can?

**Comment by philmmanjaro** [comment] 2017-10-06 12:44
On Manjaro it works. I don't know if Arch has some different than we have.

**Comment by pmargeti34** [comment] 2017-10-06 14:00
Just now 3 updates installed just fine, without forcing database refresh. Weird, since I haven't rebuilt the package since this was re-opened. So now it works as it should. Thank you philm and guinux. Closing

**Comment by RichardPIS** [comment] 2017-12-07 10:13
Phil: "On Manjaro it works. I don't know if Arch has some different than we have."

I don't know either, but it works in Manjaro, but stopped working in Arch.

**Comment by RichardPIS** [comment] 2017-12-12 09:44
Today Pamac found updates for packages in the AUR, but not in the regular database.. :/

**Comment by philmmanjaro** [comment] 2017-12-14 19:40
In which OS? On Manjaro we currently only updating **testing** and **unstable** branches.

**Comment by RichardPIS** [comment] 2017-12-14 20:28
On Arch.

**Comment by RichardPIS** [comment] 2017-12-28 15:05
For the past two weeks Pamac found updates, every day, perfect.
I don't know why, but it did.
Today it stopped again...

(On Arch)

**Comment by tHubig** [comment] 2018-03-16 15:12
This happens to me from time to time on Manjaro, too: Pamac says the system is "up to date," but
`pacman -Syyu` says there are loads of updates needing to be installed.

Lately, pamac has said my home laptop is "up to date" since March 1st, but my work laptop needed updating last sunday.  Same packages, same Manjaro.

Whatever... I'll just use pacman.

**Comment by kq01526** [comment] 2018-03-28 01:54
I also noticed this.

Clicking on Menu -> Refreshing databses did solve the issue.

Looking at this thread though, the question is for how long it will be solved and if it will re-appear.

**Comment by kq01526** [comment] 2018-03-28 17:45
@guinux @lots0logs  And the issue is back. So, "Menu -> Refresh databases" only solves it temporarily.

**Comment by philmmanjaro** [comment] 2018-03-28 17:49
Where the **systemd timers** [fixed](https://github.com/manjaro/packages-extra/commit/efd130f5d294fd8c2a098d3101118e1ca457f66f#diff-a84798fe3c7f0bd4fbe6e7330ef6a3a8) in **pamac-aur**?

**Comment by kq01526** [comment] 2018-03-28 19:41
@philmmanjaro Not sure. Would you be able to tell from those:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pamac-aur
https://aur.archlinux.org/cgit/aur.git/tree/pamac.install?h=pamac-aur

?

Regards

**Comment by kq01526** [comment] 2018-03-28 19:55
Apparently it has now been reported in the comments of pamac-aur and pamac-aur-git:

https://aur.archlinux.org/packages/pamac-aur/
https://aur.archlinux.org/packages/pamac-aur-git/

**Comment by lots0logs** [comment] 2018-03-29 00:40
@philmmanjaro Let's reopen this issue. I will dig into it further this weekend and submit a PR.

**Comment by philmmanjaro** [comment] 2018-03-29 05:52
@lots0logs: sure. I think we will find a solution.

**Comment by RichardPIS** [comment] 2018-03-29 09:34
Pamac works fine on Manjaro. It always did.
On Arch it works perfect for about a week.

The notifier turns red and updates are shown, community and AUR.

**Comment by kq01526** [comment] 2018-03-29 15:17
@philmmanjaro @lots0logs The systemd timers have now been fixed in pac-aur-git, see:

**Comment by kq01526** [comment] 2018-03-29 15:19
@philmmanjaro @lots0logs However, the issue is still there, even with the system timers fix.

You always have to click on "Menu -> Refresh databases" for pamac to find updates.

Otherwise it will always says "Your system is up-to-date" even though it is not.

**Comment by kq01526** [comment] 2018-03-29 16:24
@philmmanjaro @lots0logs Also, it would be appreciated if you could also have a look at a similar issue:

When you set pamac-updater as a startup application in GNOME Tweaks, when pamac-updater then starts as a startup application, it also always says "Your system is up-to-date" even though it is not. When you start it again manually, it suddenly finds the updates (as long as you are not affected by the mandatory "Menu -> Refresh databases" clicking issue).

Is there a reason why pamac-updater is unable to immediately find updates when it launches as a startup application? Why does it have to be launched a second time manually in order to find updates?

**Comment by philmmanjaro** [comment] 2018-03-29 19:02
@kq01526: **pamac** was designed for Manjaro. There we update our **stable** branch about once a week. Therefore it is enough to look every six hours for new updates. We don't want to bother our users always with notifications. For Arch it might be a differnt story as updates might happen daily or even more often.

**Comment by kq01526** [comment] 2018-03-29 22:22
@philmmanjaro I am using pamac on vanilla Arch / Antergos though and there updates come in immediately, which pamac should also pick up, shouldn't it?

**Comment by lots0logs** [comment] 2018-03-30 08:19
@philmmanjaro I have a fix that seems to work locally but will need to be tested. PR incoming...

**Closed** 2018-03-30 09:05 UTC

**Comment by kq01526** [comment] 2018-03-31 12:39
@lots0logs @philmmanjaro 

https://aur.archlinux.org/packages/pamac-aur-git/ includes the fix now and, at least so far, it seems to have solved the issue :slightly_smiling_face: .

Now pamac even finds updates when it's set up as a startup application via GNOME Tweaks :slightly_smiling_face: .

Thanks :slightly_smiling_face: .

**Comment by RichardPIS** [comment] 2018-04-01 17:41
I' ve installed pamac.git instead of the regular pamac-aur, but to no avail.
Pamac-aur dit even a better job and found updates untill today, git did not.

I noticed that during installation of pamac-git or pamac-aur a message passes by, it says "Program pacman-mirrors found: NO" 
Maybe this is of some importance.

**Comment by guinux** [comment] 2018-04-01 17:54
It's just a checking for pacman-mirrors which is only available in Manjaro in order to add or not some systemd timers.
It simply does nothing in Arch.

**Comment by kq01526** [comment] 2018-04-01 20:01
@RichardPIS

Here everything still works fine. With pamac v6.2.7 it finds updates better than ever, it's absolutely reliable now.

Are you sure you are using https://aur.archlinux.org/packages/pamac-aur-git/ ?

**Comment by RichardPIS** [comment] 2018-04-01 20:36
Yes, pamac-aur updated fine for the last week or so, pamac-aur.git did nothing so i reinstalled the first one.

**Comment by RichardPIS** [comment] 2018-04-02 15:01
And installed pamac-aur-git again. ;)
And it did not find updates, not even after I've refereshed the database.
(terminal says that there are updates available..)

**Comment by philmmanjaro** [comment] 2018-04-02 20:34
@RichardPIS: **Pamac** is mostly designed to work on **Manjaro** and its setup. We do our quality checks on our OS. You can check our [changelog](https://github.com/manjaro/pamac/compare/v6.2.5...master) to see which changes got made since **v6.2.5**. When I start my PC it finds the updates just right.

**Comment by RichardPIS** [comment] 2018-04-02 22:08
Philip, i am aware of the fact that pamac was designed for Manjaro and it runs perfect on my Manjaro laptop and also on one desktop with Arch.

Curious is though that it works intermittend on another desktop with Arch.

The difference between those two is the desktop. 
The one with Gnome works okay, the one with xfce doesn't.
I can't stand it that I can't seem to figure out why.

Good job, by the way, by making such a great app!
