### ISSUE TITLE
Automatic updating to be an option

### ISSUE THREAD

**Issue by es20490446e** [manjaro/pamac#364] opened 2017-11-08 14:37 UTC
It would be nice if Pamac could install updates automatically without proms, and only ask for user intervention if there's an abnormal situation.

**Comment by notramo** [comment] 2017-11-27 11:26
I think updating system without notify isn't good, but only downloading updateable packages to cache would be cool. Then Pamac would notify the user that there are updates, and after clicking OK, it would start installing without having to wait for download.

**Comment by es20490446e** [comment] 2017-11-27 14:50
Notifying is good when there is an abnormal situation, or when the user explicitly asks for it. The rest of time it does nothing.

**Comment by es20490446e** [comment] 2017-11-27 14:52
The risk will be exactly the same, if people are presented with an update they will just update. The security of user intervention is just a mirage.

**Comment by notramo** [comment] 2017-11-27 19:48
One problem with updating, that a dependency is updated but a program that requires it isn't yet updated. For example, `blender` depends on `boost-libs`. It is compiled against one version of `boost-libs`, and doesn't work with different version. Pamac starts updating, it updates `boost-libs`, then other packages, then `blender`. What happens if the user launches `blender` in that status of the update (`boost-libs` is updated, but `blender` isn't yet)? It will crash, because it finds a different version of Boost libs on the system than the one it was compiled against.
Also, the user can get similar error, if a large package is currently in progress (for example `libreoffice-fresh`), and only part of the new version is extracted to the filesystem. It can crash in that case also.

What about when the user shuts down the machine, because he doesn't know that a transaction is in progress? Also, it can be a problem if the user supends the machine while updating. It maybe can't wake up.

Why I think that downloading only would be a good solution:
If the user shuts down the machine while downloading, the next update will download again the last file that isn't finished, then continues with other packages.
When a laptop is on low battery level (or there is some reason for shutting down the machine quickly), the user can choose not to update.
The user will always know the updated packages and not wonder if some programs doesn't start while updating.

**Comment by es20490446e** [comment] 2017-11-27 22:25
I see, all makes sense.

**Comment by es20490446e** [comment] 2017-11-27 22:26
Yeah, I agree with your proposal. Thanks for your attention ;)

**Comment by polarathene** [comment] 2018-05-16 04:41
I don't quite understand the blender issue you're providing. That'd happen with Pamac manually if you updated just that lib no? An automatic update should work with the package manager like it does manually, you wouldn't get a new update to boost-libs if blender is holding it back, else blender would have an update. If the blender package is in the AUR that might not be the case though(I've had AUR packages break because main repos updated a package or were outdated to AUR dependencies).

I do like having the option to automatically download the updates, maybe even automatically compile the AUR ones too(not sure if you can do that before the install/move part of the update).

EndlessOS now supports automatic updates btw: https://www.phoronix.com/scan.php?page=news_item&px=Endless-OS-3.4-Released

**Comment by notramo** [comment] 2018-05-16 12:09
>I don't quite understand the blender issue you're providing. That'd happen with Pamac manually if you updated just that lib no? An automatic update should work with the package manager like it does manually, you wouldn't get a new update to boost-libs if blender is holding it back, else blender would have an update. If the blender package is in the AUR that might not be the case though(I've had AUR packages break because main repos updated a package or were outdated to AUR dependencies).

The problem is not this. Read my comment again.

>I do like having the option to automatically download the updates, maybe even automatically compile the AUR ones too(not sure if you can do that before the install/move part of the update).

I also would like having the option to automatically download the updates (as I wrote in my previous comment, read it again).
I think automatically compiling AUR packages can be problematic on old machines, because it requires almost all the CPU, and sometimes a lot of RAM. If somebody has a running browser, and office, the compiling can freeze their system.

**Comment by guinux** [comment] 2018-05-26 14:52
duplicate of #216

**Closed by guinux** 2018-05-26 14:52 UTC
