### ISSUE TITLE
Pamac v4.0 feedback

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/pamac#113] opened 2016-04-09 09:43 UTC
Hi all,

Guillaume was working for some time on a new design for **pamac**. Even if there is still some work to do, he wants some feedback on the work he had done so far. That for he proposed a preview version.

It has a new design:

- double click on a package name to view details.
- in dependencies view, click on a dependency to view its details
- you can continue browsing packages while a transaction is running

So tell us what you think about it ...

---

**How to install**

Unstable branch
```
sudo pacman -Sy pamac
```

Any branch
```
sudo pacman -U http://mirror.netzspielplatz.de/manjaro/packages/pool/overlay/pamac-4.0rc3-1-$(uname -m).pkg.tar.xz
```

---

**Images**

![pamac-package-view](https://cloud.githubusercontent.com/assets/5050022/14763612/dc7bed10-099a-11e6-8b0b-f42f6dd1eee7.jpg)
The new overview

![pamac-dependency-view](https://cloud.githubusercontent.com/assets/5050022/14763614/e4a37c88-099a-11e6-9d70-8337e267897e.jpg)
The new dependencies view

![pamac-settings](https://cloud.githubusercontent.com/assets/5050022/14763615/eac2bbf6-099a-11e6-9d17-0b9e33127e9c.jpg)
The new settings view

**Comment by kouros17** [comment] 2016-04-09 10:21
I like it so much and works without issues so far.
The most important for me is that we can see now the repo of official packages even after their installation (no more as a "local" package after the installation). :+1:

**Comment by Stebs** [comment] 2016-04-09 11:44
Looks nice.
Whishlist (for parity with octopi):
Optional integration of a cachecleaner, just like octopi-cachecleaner and maybe also pacmanlogviewer (usefull if one not only uses pamac to install).

For pamac-updater: (optionally?) see old and update-version of packages side-by-side.

**Comment by johnvan54** [comment] 2016-04-10 00:42
Looks very nice. I like the information about the packages available on the initial screen (description / repository / version).

**Comment by lots0logs** [comment] 2016-04-10 02:12
@philmmanjaro It's definitely an improvement over the current release version. Is there any reason why the work was not done on github? The reason I ask is because the UI could use some love and I would be happy to contribute (especially considering that we ship Pamac by default)

**Comment by philmmanjaro** [comment] 2016-04-10 09:52
@lots0logs: ask @guinux about it. He did it on his local pc. Seems he wanted just to get some info and present the final version to the public. However you can use the source provided by him and push it to your **pamac** fork. I'm sure @guinux will share his work soon or later also as source to the public ...

**Comment by guinux** [comment] 2016-04-10 11:44
@lots0logs: I just wanted some feedback first but of course there is no problem if you want to contribute.

**Comment by lots0logs** [comment] 2016-04-10 11:49
@guinux Oh okay. No worries. I can wait until you're ready :wink:

**Comment by philmmanjaro** [comment] 2016-04-10 11:56
@guinux: AUR support is totally broken and starts a clusterfuck. Please check it once again. Current v3.x release is not affected by this. Seems to be a v4.x regression only.

**Comment by kouros17** [comment] 2016-04-10 14:52
I can't install a package with right click.

**Comment by beardedragon2** [comment] 2016-04-10 20:49
Nice and neat.  It's a keeper.

**Comment by guinux** [comment] 2016-04-13 13:14
@philmmanjaro: What did you test exactly in AUR?

**Comment by philmmanjaro** [comment] 2016-04-13 18:36
@guinux: I just tried to enable it by checking all checkboxes. Then somehow the message for new packages came in a loop until I killed the pamac panel client. Also my PC almost froze due heavy load. If it works at all I had not time to check as my PC was already blocked ;)

**Comment by lots0logs** [comment] 2016-04-13 19:13
@guinux I can also confirm that it doesnt work for installing packages. You can search but you cant install. I didnt have time to do any proper debugging yet. Sorry!

**Comment by beardedragon2** [comment] 2016-04-13 21:57
I just used it to install and build acroread-fonts-systemwide and then 
got notice to upgrade and built google-chrome.  It worked for me in AUR

**Comment by guinux** [comment] 2016-04-14 16:22
just pushed new code as [v4.0.0-beta](https://github.com/manjaro/pamac/commit/b59e68459b9c0f0f841ae38fedbc572171a2ca69), please try agin and report ;)

**Comment by philmmanjaro** [comment] 2016-04-14 16:55
**v4.0-beta1** fixes the **AUR issues** I had reported.

**Comment by philmmanjaro** [comment] 2016-04-14 16:59
Tray-icon still shows updates, even if the system is fully updated ...

**Comment by beardedragon2** [comment] 2016-04-14 17:24
No problems with tray-icon.

/home/bob/Downloads/Screenshot_2016-04-14_12-21-40.png
/home/bob/Downloads/Screenshot_2016-04-14_12-22-14.png

**Comment by kouros17** [comment] 2016-04-14 20:54
v4 fixes the issue I had reported (I can't install a package with right click. The box remain untick although I have chosen.). Without issues so far.

**Comment by philmmanjaro** [comment] 2016-04-15 06:08
@guinux: forget my report for the tray-icon. It works. Was the change from **pamac** to **pamac-dev** which broke the connection :smile:

**Comment by fallenskillz** [comment] 2016-04-15 06:56
I've just installed it on KDE Daniella Pre2, very nice, it slides when double clicking on a package name to focus on details. First time using it and I'm keeping it. So far so good, thank you!

**Comment by kouros17** [comment] 2016-04-15 08:36
I can't install optional dependencies (when I try to "install optional dependencies" of a program with right click)

**Comment by guinux** [comment] 2016-04-15 10:13
@kouros17: thanks, it's fixed.
@all: please also check translations on [Transifex](https://www.transifex.com/manjarolinux/manjaro-pamac/)

**Comment by Jarco** [comment] 2016-04-15 11:59
I like the design a lot better now. The Small buttons at the top seem out of place tough.

**Comment by benchile** [comment] 2016-04-15 19:37
it looks really cool, I like the new design and it also seems to work lighter and faster in Linux deepin. It takes less minutes to start up and close.

**Comment by lots0logs** [comment] 2016-04-17 16:15
#114 screenshot 

![2016-04-17_11-14-48-am](https://cloud.githubusercontent.com/assets/4675662/14588364/9f703f8c-048d-11e6-8ee4-4aaf507816c9.png)

**Comment by philmmanjaro** [comment] 2016-04-18 05:36
@lots0logs: Update-Manager, Settings and the other dialogs are still using the old style. However using Headerbars seems to improve the look of **pamac**. Can you check if you can unify it to the other dialogs also? Your first draft I added now to **beta3**.

**Comment by maxrot** [comment] 2016-04-18 23:47
Happy birthday Phill isn't it nice to be older lol! I like the new changes in pamac-dev it reminds me of Rigo from Sabayon Linux. The last update my xfwm window borders were replaced by a header bar, lots of people love them that is fine for them. I also use i3wm there is no borders there and the header bar does not go away. I would like to still have a version of pamac which can use metacity or xfwm window borders. We don't need to eliminate the header bar, we could have in the repo pamac with header bar or pamac with xfwm metacity borders. Thanks an Manjaro Linux Rocks!

**Comment by lots0logs** [comment] 2016-04-19 06:10
@maxrot Could you provide some screenshots showing what it looks like with any window managers that you have installed which do not fully support CSD?

**Comment by maxrot** [comment] 2016-04-19 14:40
It was my theme causing the issue. The margin was set to 10 so this caused wide borders in i3Wm with gtk3 apps. In fact now that it is fixed I have screen space. I agree we should stay with CSD. Sorry It was only a problem with theming. I am sending from my phone I can not make screenshots. Thanks.

**Comment by maxrot** [comment] 2016-04-19 21:44
Wow in the last update the xfwm window managers are back. I appreciate that but there really should be an option in the Ofificial Repos, for those that would like to use header bars in pamac-dev! If it is possible.

**Comment by maxrot** [comment] 2016-04-19 21:53
Or if it is possible we could add in the preferences an option to use header bars or not. That would be cool if Gnome would do that with all of their apps.

**Comment by philmmanjaro** [comment] 2016-04-19 22:08
@maxrot: I've reverted @lots0logs patch for now in **beta3-2** since it created some issues with functionality in regard of **AUR** support disabled. However, we will work on getting it Headerbar ready ...

```
sudo pacman -U http://mirror.netzspielplatz.de/manjaro/packages/pool/overlay/pamac-dev-4.0beta3-2-$(uname -m).pkg.tar.xz
```

**Comment by maxrot** [comment] 2016-04-20 00:29
I have also noticed that with the xfwm and metacity borders when I maximize the window there is less space in the package listing area. But with the Headerbar there is more space in the package listing area.

**Comment by maxrot** [comment] 2016-04-20 00:38
These are the screenshots so you know what I mean.
![pamacheaderbar](https://cloud.githubusercontent.com/assets/18541214/14659977/eb5a3000-06a0-11e6-8903-086a013b940b.png)
![pamacxfwm](https://cloud.githubusercontent.com/assets/18541214/14659982/f0418870-06a0-11e6-8267-0fe6b2c503ed.png)

**Comment by lots0logs** [comment] 2016-04-20 00:44
@philmmanjaro I don't understand the reasoning behind going backwards instead of forwards. This is the `dev` version of Pamac after all so it should be perfectly acceptable that issues are still being worked on. I could understand if this wasn't the `dev` version but honestly, at this point I don't know whether or not I should continue to work on my improvements (based on the mixed feedback from you guys) :confused:

**Comment by maxrot** [comment] 2016-04-20 04:19
I appreciate your work I mention issues so they can be fixed. I also like the Header bar because it gives more space in the package listing area as you can see in the screen shot. Keep your head up be strong I support whatever decision is made. Now all you have to do is fix the AIR issue. With the other suggestions I said if possible if not than it is OK. Keep up the good work keep your head up and be strong.

**Comment by lots0logs** [comment] 2016-04-20 05:03
@maxrot Thanks. I was not referring to any of the feedback you provided. I don't want to make something out of nothing by explaining further as I'm pretty sure @philmmanjaro knows what I am talking about. Anyway, thanks again for your comments :smiley:

**Comment by guinux** [comment] 2016-04-20 07:38
Maybe I will have some time to work on headerbar today for all windows. Just now that for dialogs it means that the buttons will be on the top, in the headerbar.

**Comment by philmmanjaro** [comment] 2016-04-20 17:56
@lots0logs: We will change to **headerbar** for sure. However was the **AUR** support broken and other features @guinux introduced by applying your patch. The revert was just to get the other feedback we need from the community. Your patch isn't yet included in the **pacman-dev** package. However I can add your patch to the **pacman-exp** package, which can be totally broken ;)

**Comment by guinux** [comment] 2016-04-23 15:32
Just pushed my work. I added headerbars all windows. I also try to improve updater.
Try and report ;)

**Comment by philmmanjaro** [comment] 2016-04-23 20:12
Somehow **pamac** don't start in the center in **XFCE**. At least for me in the upper right corner of the screen.

**Comment by neil1969** [comment] 2016-04-23 20:32
I really like the look of it, but most importantly I like the fact that the repo of origin is now readily available for installed packages.

**Comment by Ste74** [comment] 2016-04-23 20:44
In Gnome and Budgie no issue

**Comment by kouros17** [comment] 2016-04-23 20:51
@philmmanjaro  it depends on the theme. You have to comment out (or delete) the "placement_ratio" line in /usr/share/themes/your theme/xfwm4/themerc.
Take a look here:
http://winaero.com/blog/fix-window-centering-in-xfce-does-not-work-properly/

**Comment by philmmanjaro** [comment] 2016-04-23 21:43
@kouros17: the **vertex-maia** themes don't have **placement_ratio** inside of **xfwm4/themerc**. The updater is placed as wanted, only the manager has the issue always starting on the upper right corner in XFCE.

**Comment by philmmanjaro** [comment] 2016-04-23 22:15
@kouros17: I found the issue. I had to higher the **placement_ratio** value to **60** to have it centred now.
```
<property name="placement_ratio" type="int" value="60"/>
<property name="placement_mode" type="string" value="center"/>
```

**Comment by kouros17** [comment] 2016-04-24 01:37
Nice! :+1:

**Comment by johnvan54** [comment] 2016-04-24 02:31
Works and looks good.

**Comment by philmmanjaro** [comment] 2016-04-24 06:30
Please check out if your language still needs some [translations](https://www.transifex.com/manjarolinux/manjaro-pamac/) ...

**Comment by Photon89** [comment] 2016-04-24 09:10
It's not a problem of Pamac itself but of GTK3 apps in general, but I absolutely dislike the fact that essential functionality (like Update and Apply buttons) is now hidden behind some generic gear wheel button. I see two problems with it: 

1. Inexperienced users won't find the Apply and Update buttons and therefore the whole program will be useless for them.
2. Even for experienced users it's bad in terms of usability (two clicks instead of one are necessary).

Of course, the first point is more important here. One can argue that inexperienced users should not use a package manager themselves anyway, but the same applies to other Gnome software like the PDF reader Evince, where inexperienced users are completely unable to find the Print button which is hidden behind a gear wheel button.

**Comment by kouros17** [comment] 2016-04-24 09:54
I agree that there should be the three buttons of the "old pamac" (refresh, apply, cancel) separately and to the left of headerbar

**Comment by guinux** [comment] 2016-04-24 10:15
In package manager if you select a package for install or removal, the buttons will appear in the bottom of the window.
In updater, if some updates are available, the apply button will appear in the bottom of the window.

**Comment by fallenskillz** [comment] 2016-04-24 15:40
To be slightly off topic on for the "new users" as a noob using Linux for a couple of months now, I've found all "friendly" distros not far to some side-ways on how to install software from one to another.If I'm unsure about how things work, It's a matter of figuring it out and googling about it. I think people are prepared to learn and want to learn, they wouldn't be lurking into Arch or even Manjaro in the first place.
 Not to be an A, but how far the distros need be holding "new users" hands (Ubuntus job ain't it? :)0). There is helpful and a great community and team that do want to help and I'm very grateful for that also but I like to figure out things by myself most of the time, but I think those that explore are smart enough to find hamburger and  gear wheels. If it's going to be frustrating why explore the unknown in the first place?  I'm just saying :). Great job and go Manjaro.

**Comment by maxrot** [comment] 2016-04-25 00:47
How can I make a pkg for the AUR to offer Pamac with normal window borders? @philmmanjaro Non CSD.

**Comment by philmmanjaro** [comment] 2016-04-25 08:13
@maxrot: why? We will use CSD from now on. However you can revert followed commits if you must: https://github.com/manjaro/pamac/commit/f0ac44bc4fd1080e04bee24479f213a9b152b351 https://github.com/manjaro/pamac/commit/6046da77297346367276602cf8449b579dc7950a

**Comment by Photon89** [comment] 2016-04-27 10:31
@fallenskillz: I don't think, Manjaro should give up the race for the user friendliest distro without even trying. Actually, in 2004-2005, when Ubuntu has been introduced it was something very special because it offered a LiveCD and a graphical installer. I think, Knoppix was the first distro to offer a LiveCD mode but it had no graphical installer, so Ubuntu was the first distro to offer such a package. That's what gave it so much popularity and made it the number one distro for beginners. Neither had it a big community nor a good documentation in these early days, it was a plain technological aspect which made Ubuntu so successful.

But nowadays most of the distros offer what Ubuntu offers. Of course, Ubuntu had a head start and therefore has a big community and thus a great documentation (I use the German site ubuntuusers.de a lot even though I don't run any of the *buntu flavours for years already). But in terms of technology I don't see any particular advantage of Ubuntu compared to other distros as Mint or Manjaro. I think, as of today, the user-friendliness of a distro is rather measured by the number of problematic updates. Here, in my experience, Ubuntu has both light and shadow as compared to Manjaro, though the package updates are slightly less likely to cause problems (mostly thanks to AUR packages), the big updates are much more likely to do so (mostly thanks to PPAs). 

In total, in my view Manjaro has enough potential to become the number one distro for beginners, though it will be hard to fight Ubuntu which has already a lot of momentum. I actually help several absolute beginners to administrate their Manjaro systems and it works surprisingly well.

@guinux: Thanks, now I actually tested Pamac rather than just looking at the screenshots and see what you mean. This looks good to me, then! Just one proposal: In the details page (what opens if you double click a package) I'd propose to add an install/remove button. Usually, once you are in the details page you decide what to do with the package, so it is uncomfortable to have to go back to the package list and then install/remove the package there. By the way, the possibility to go back with the thumbs buttons of the mouse like in an internet browser would be great!

**Comment by philmmanjaro** [comment] 2016-04-27 10:54
@Photon89: the button to install or remove dependencies should be easy to be added ...

**Comment by guinux** [comment] 2016-04-27 11:17
@Photon89: thanks for your ideas, I will add them in my TODO list :)

**Comment by uncles-a-m** [comment] 2016-04-27 13:14
I like it! 
Up to now: no issues with Gnome 3.20 or Cinnamon 3.0.
A button to install or remove dependencies would be very comfortable...

**Comment by fallenskillz** [comment] 2016-04-27 14:48
@Photon89   Greetings and thanks for the reply and for the little interesting history (Knoppix ayy). Yes, your right without gui's and user-friendliness with the founders, teams and community great work making it possible for us new users have a good experience and I really I appreciate it that. It would be intimidating and confusing the first place, I'm not saying that Manjaro should give up, 
Manjaro doing a fantastic job as it is on what I've seen and read about Manjaro is on top best distros as it should be and more up the better. And as a  great successful project, I think Manjaro shot up faster than Ubuntu did in years that's more than successful no? :). Ain't Manjaro climbing faster than any other distros? Why is that? Or I'm I wrong...

To be honest, when I heard of Arch, Manjaro etc..I thought I had to be equipped with ninja tools tools and Torvalds knowledge (shoot I wish), :) but lucky that the teams work (in all distros) made it possible for others and myself not to but meaning not that they want to. :)
What I was trying to say is that about being user-friendly it is already a job well done, making it possible to explore even more and thank you. I guess I'm lucky I came at the right time but wished I did a long time ago. Cheers...

(Please excuse my writing nor grammar. Oh and Ubuntu is great but in a certain time it crashed on me enough to try something else...)

**Comment by Zzooouhh** [comment] 2016-04-30 20:24
I hate to be the token party pooper, but I am not liking this redesign at all. The previous one wasn't flawless, but it was quite practical and snappy to use. I'm definitely biased here since I consider Gnome3's aesthetics and general UI design scheme (which this is very much consistent with) a disaster, and some of its UI decisions completely unintuitive (confirm/cancel buttons in the title bar? even when there is a gaping empty bezel on the bottom?).

But there are some changes here that I can't think of in any other way than objective regressions: the details sheet is hidden by default and accessing it requires two clicks, whereas on the old UI it only required selecting the package name and didn't obscure every other part of the UI. The top button menu is a lot more confusing to navigate and feels out of place from a design standpoint; it made logical sense for the UI to be separated into two portions (left was always selecting/querying repos, right was packages/details) here it's just just mingling one over each other with no hard separation. Keyboard navigation in general took a big hit, and I can't seem to make sense of how to reliably select packages and install them without tabbing or shift-tabbing through like a dozen buttons and windows; the older version could've used some keyboard shortcuts, and maybe a tad more 'tab-friendly' interface too, but this one seems to be definitely a step in the opposite direction from my point of view.

**Comment by philmmanjaro** [comment] 2016-05-01 10:30
@Zzooouhh: well, we got also a lot positive feedback regarding the new design. Sure, we can always improve it.

**Comment by uncles-a-m** [comment] 2016-05-02 10:10
I got one little issue with the settings-dialog. The option "remove unnecessary dependencies" (Entferne nicht benötigte Abhängigkeiten) is always disabled. I enabled it, but reopening the settings-dialog, it is disabled again.

Is this a misconfiguration of my system, or ist there anybody else with this issue?

**Comment by palob** [comment] 2016-05-02 10:59
I dig the new layout.
I'm wondering whether the search field could look better with a few px padding around.
![padding](https://cloud.githubusercontent.com/assets/7050624/14952931/3509f3b6-1065-11e6-8a48-049566098f18.png)
Just the way it looks on the right side:
![padding2](https://cloud.githubusercontent.com/assets/7050624/14952965/64d9b2ac-1065-11e6-9dbc-31b3424d439e.png)

I think the repo/AUR switch 
![switch](https://cloud.githubusercontent.com/assets/7050624/14952992/92fc5158-1065-11e6-9dde-97692f9eb5ef.png)
Since there's already a View Switcher in the header bar it looks a bit busy with two of those.
should be replaced by tabs like it was before.

**Comment by philmmanjaro** [comment] 2016-05-02 12:25
@palob: excelent review. the column widht was also something I wanted to be changed. However this is only optical, so I didn't mentioned it yet.

**Comment by kouros17** [comment] 2016-05-02 20:23
I made some changes for the greek language.
https://www.transifex.com/manjarolinux/manjaro-pamac/language/el/
https://www.transifex.com/manjarolinux/manjaro-pamac/language/el_GR/

**Comment by prescott66** [comment] 2016-05-03 15:18
I like changes that was made in 4.0 RC. I just miss progress bar while installing/downloading packages.

**Comment by maxrot** [comment] 2016-05-03 15:36
I like what I see only one thing is missing! It was also in Pamac 3. The adjuster bars. Where someone can resize the window frames in the inside. I hope you understand I miss this.

**Comment by maxrot** [comment] 2016-05-03 15:45
![pamac3](https://cloud.githubusercontent.com/assets/18541214/14989142/ba6ffbda-1156-11e6-86c0-6ef162a1649c.png)
![widgetfactor](https://cloud.githubusercontent.com/assets/18541214/14989144/bf6bfe40-1156-11e6-9bbb-708aca3a0c83.png)

the dotted lines is what I mean is not in the new pamac

**Comment by maxrot** [comment] 2016-05-03 15:47
I have also a steam error. It won't start!

Running Steam on manjarolinux 15.12 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1459463254)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

I hope you can help I think it is a problem with xf86-video-intel. @philmmanjaro

**Comment by philmmanjaro** [comment] 2016-05-03 16:35
@maxrot: The steam issue is already explained in our update announcement under **troubleshooting**. Also it is is offtopic in this thread.

**Comment by maxrot** [comment] 2016-05-03 16:37
Thank you! Sorry!

**Comment by M1cha** [comment] 2016-05-04 07:10
the updater can be closed during an update. This kills the pacman process(and leaves a dead lockfile).
Also, on reopening pamac becomes unusable(just an empty window frame), maybe a message "pacman is in use" would be great.

**Comment by guinux** [comment] 2016-05-04 09:35
Did you test it because the process should continue in background without trouble.

**Comment by M1cha** [comment] 2016-05-04 09:46
yes :) also, I just noticed that there's no progress indicator while updating the sources, the window is just unresponsive.

**Comment by guinux** [comment] 2016-05-05 11:18
Thanks for the report, it should be fixed now ;)

**Comment by philmmanjaro** [comment] 2016-05-06 22:33
**4.0-rc3** is now online.

**Comment by M1cha** [comment] 2016-05-07 13:22
I could post this as a new issue but since it's kinda related to the new UI I just post this here.
can you make the package details page react on the back key of the mouse?

**Comment by ItachiSan** [comment] 2016-05-09 06:29
Hello there!
I wanted to say this, as I really like the new style.
I just have two really minor things to report for the updater:
* make the updater information boxes to stretch accordingly to their text
* add a progress bar on the lower area; as of now, the progress is shown only by text message, not giving an idea of the actual progress. (Or maybe a percenteage message can be added...?)

**Comment by markmuir87** [comment] 2016-05-10 11:36
A few issues/suggestions:

1. A little embarrassing to admit this, but I only found out about the 'details view double click' thing from reading this issue. I'd actually installed octopi on my system because I thought pacmac had become too 'dumbed down'. Is there some way of making this functionality obvious to new users? It's somewhat counter-intuitive, as I suspect the more common assumption would be that double click selects a package for install.

2. For the 'detailed view' for Aur packages, it would be awesome to have a third tab which provides recent comments made on the package page. These often provide valuable information (in some cases, warning you that the latest build is broken). Octopi doesn't have this feature (as far as I can tell), so could be a nice way to differentiate.
  * I've never contributed to a OS project like this before, so not sure how it works, but if you'd like I could write a scraper in python for you. 

3. Bring back the integrated bottom pane details view, or maybe make it a non-default optional setting? It's much more efficient than having to double click on the package and then mouse over to a button to go back (maybe having a default 'mouse back key' short-cut here would help). 

4. Another vote here for the progress bar. 

5. Might also be nice to have the opening of the terminal window integrated in to the original window (similar to how the details view for a package slides in to view). Otherwise it just feels a bit jarring.

**Comment by amasz3gr** [comment] 2016-05-12 13:03
> double click on a package name to view details.

I update Pamac yesterday and it was very confusing. I do not see the purpose of this change.
Except for this inconvenience, very nice job. No other issues so far.

**Closed** 2016-05-13 21:40 UTC
Labels: feedback
