### ISSUE TITLE
[compile error] preferences_dialog.vala:276.34-276.37: error: Argument 1: Cannot pass value to reference or output parameter

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/pamac#252] opened 2017-05-10 08:49 UTC
Hmm, I get an compile error with this:

```
==> Retrieving sources...
  -> Found pamac-4.3.4-2.tar.gz
  -> Found fix-aur-only-build.patch
==> Validating source files with sha256sums...
    pamac-4.3.4-2.tar.gz ... Passed
    fix-aur-only-build.patch ... Passed
==> Extracting sources...
  -> Extracting pamac-4.3.4-2.tar.gz with bsdtar
==> Starting prepare()...
patching file src/transaction.vala
==> Starting build()...
cd resources && make resources
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/build/pamac/src/pamac-4.3.4/resources'
glib-compile-resources pamac.transaction.gresource.xml --target=transaction_resources.c --generate-source
glib-compile-resources pamac.manager.gresource.xml --target=manager_resources.c --generate-source
glib-compile-resources pamac.updater.gresource.xml --target=updater_resources.c --generate-source
glib-compile-resources pamac.installer.gresource.xml --target=installer_resources.c --generate-source
make[1]: Leaving directory '/build/pamac/src/pamac-4.3.4/resources'
cd src && make binaries
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/build/pamac/src/pamac-4.3.4/src'
valac 	-o pamac-refresh \
		-X -w \
		--pkg=gio-2.0 \
		--pkg=posix \
		pamac_config.vala \
		refresh.vala
pamac_config.vala:124.3-124.19: warning: method `Pamac.Config.write' never used
		public void write (HashTable<string,Variant> new_conf) {
		^^^^^^^^^^^^^^^^^
Compilation succeeded - 1 warning(s)
valac 	-o pamac-daemon \
		-X -w --pkg=posix -X -DGETTEXT_PACKAGE="pamac" --target-glib=2.38 \
		--pkg=libalpm --pkg=gio-2.0 --vapidir=../vapi -X -D_FILE_OFFSET_BITS=64 \
		--pkg=polkit-gobject-1 \
		--pkg=libcurl \
		--pkg=json-glib-1.0 \
		--pkg=libsoup-2.4 \
		--thread \
		alpm_config.vala \
		common.vala pamac_config.vala \
		package.vala \
		aur.vala \
		mirrors_config.vala \
		daemon.vala
valac 	-o pamac-tray \
		-X -w --pkg=posix -X -DGETTEXT_PACKAGE="pamac" --target-glib=2.38 \
		--pkg=gtk+-3.0 \
		--pkg=libnotify \
		common.vala pamac_config.vala \
		tray-gtk.vala \
		tray.vala
pamac_config.vala:124.3-124.19: warning: method `Pamac.Config.write' never used
		public void write (HashTable<string,Variant> new_conf) {
		^^^^^^^^^^^^^^^^^
Compilation succeeded - 1 warning(s)
valac	-o libpamac.so \
		-X -fPIC \
		-X --shared \
		-H pamac.h \
		--vapi=pamac.vapi \
		--library=libpamac \
		-X -w --pkg=posix -X -DGETTEXT_PACKAGE="pamac" --target-glib=2.38 \
		--pkg=gtk+-3.0 --pkg=gdk-3.0 --pkg=vte-2.91 -X -lm \
		--gresources=../resources/pamac.transaction.gresource.xml \
		../resources/transaction_resources.c \
		common.vala pamac_config.vala \
		package.vala transaction.vala history_dialog.vala choose_provider_dialog.vala transaction_sum_dialog.vala progress_box.vala \
		preferences_dialog.vala choose_ignorepkgs_dialog.vala mirrors_config.vala
preferences_dialog.vala:276.34-276.37: error: Argument 1: Cannot pass value to reference or output parameter
				ignorepkgs_liststore.remove (iter);
				                             ^^^^
Compilation failed: 1 error(s), 0 warning(s)
make[1]: *** [Makefile:94: libpamac.so] Error 1
make[1]: Leaving directory '/build/pamac/src/pamac-4.3.4/src'
make: *** [Makefile:14: all] Error 2
```
Seems to be some changes with **testing** branch.

**Comment by philmmanjaro** [comment] 2017-05-10 08:51
Maybe some issue with **vala 0.36.3-1** ... See also [here](https://gist.github.com/philmmanjaro/62937585f23bd7356f3a29a4fdff1150).

**Comment by guinux** [comment] 2017-05-10 12:01
Duplicate of #235

**Closed** 2017-05-11 11:31 UTC
