### ISSUE TITLE
The new layout is absolute garbage.

### ISSUE THREAD

**Issue by NolanSyKinsley** [manjaro/pamac#302] opened 2017-09-18 04:34 UTC
Seriously, why swap areas like this? Why change theCommunity/AUR selection from the top and place it where search results used to be? This isn't a browser, people open pamac and search first, then maybe browse. You have added an extra step in order to search now... The search bar should be present and available as soon as pamac is opened, rather than requiring a further click to get to...

I know, this may seem a bit nitpicky, but usability is one of my pet peeves. The latest update has taken a step back in usability. One used to be able to open the program, type in a query, and then select a package or two to be installed with just two or three clicks... Now it is not the case. The search function should be up front and center as soon as you open the UI, PERIOD. That is what most people use first, so it should be what is presented and available first with the least effort. This update has taken a giant step back in it's usability and user friendliness.

Please revert this, or at least allow an option to revert to the old format, this new format is absolute garbage.

**Comment by pmargeti34** [comment] 2017-09-18 11:35
Search starts as soon as you type anything.

**Comment by geplus** [comment] 2017-09-18 11:44
The best thing for all type of user is to "allow an option to revert to the old format". 

I also quote my request: #299

**Comment by philmmanjaro** [comment] 2017-09-18 19:11
Since we are working on transforming **pamac** to an universal application, which also can act as a store, it was the right move we did with the new UX design. See also: https://github.com/manjaro/pamac/issues/288. Now we only have to polish it until **snaps** can be fully supported.

**Comment by geplus** [comment] 2017-09-19 17:57
@philmmanjaro  you have to consider that some people use pamac for its functions of simple, polish and functional package manager, and dont' need or dont' want to use a a store.
I understand your need of implement a store that support snaps packages (despite I'm personally dubious abou snap packs ), but you can't simply drastically alter the interface without giving the possibility to use the look anthe function of the old one (it pretty much the same of what Gnome did with Gnome 3).
The only solution I see at this point is to fork pamac 5 , or maintain pamac 5 along with pamac 6, with bugfixes only.

**Comment by philmmanjaro** [comment] 2017-09-20 08:10
@geplus: **pamac** is a **gnome** application and follows also their design. So far it worked fine and overall most are happy with the new look. We have to see what we will do about a fork of **pamac v5**.

**Comment by guinux** [comment] 2017-09-20 15:56
When I developed pamac v6, I always kept usability in mind.
Because you can type to start search as soon as pamac is started, the usage can be the same as before.
Clicking on tabs to browse packages is also as easy and fast as with v5.
If someone has real and detailed examples of usability regression I will always examine them.

**Comment by minerval** [comment] 2017-09-22 01:02
Sadly Pamac is now very slow, because it has to load all the extra Icons and so on. The first thing i did was to see the settings menu to deactivate the icons. Then i tried to make the window smaller, but the window resizes every startup. I would like to have "black/blank" buttons instead of the Symbols, so i could use a touchscreen, only frames, but without the graphical extensions.
I have everithing I need, i don´t need a magazine or catalogue, i just want to keep my system up to date.
It seems I do the opposite with Pamac than intended, because I used it to disable unwanted packages with GUI.

**Comment by joaoherberto** [comment] 2017-09-22 16:00
Absolutely love the new interface, usability is amazing and intuitive! 

Feature request: 

1. Create personal accounts to save user installed packages list
2. Group package lists by machine.
3. Add to or create custom package list.

I would be willing to pay a nominal fee per year to have this functionality.

**Comment by Campanula** [comment] 2017-09-24 02:19
I love the new interface, but also I support that the search bar should be present

**Comment by prescott66** [comment] 2017-09-24 20:11
New UI is not bad. Nice to see some progress. Time and user experience will bring tweaks and fixes.
i.e. "Select all" button in main window is useless, because it not select/check all apps in list.
       Updates window maybe needs some graphics, when pamac do something (before showing updates or "Your system is up to date")

**Comment by ratorx** [comment] 2017-09-25 16:19
I don't mind the new UI, but the search UI no longer auto switches to the AUR tab if the package doesn't exist in the default repositories. This functionality was available in the old UI. Is it possible to bring that back? Or was this deliberately changed?

**Comment by guinux** [comment] 2017-09-25 18:23
@ratorx : you're rigth it's fixed with bad4624

**Comment by startas** [comment] 2017-10-02 10:04
Yup, new ui is absolute garbage. Probably gonna have to reinstall 5.x as version 999... until it stops working, then fully go back to using superior windows os, because soon linux will because windows 13...

**Comment by geplus** [comment] 2017-10-03 13:00
@startas : I'm using version 5.1.1 at the moment. I think it should be forked and mantained with bugfixex only

**Comment by cromerc** [comment] 2017-10-03 13:18
@geplus 
I forked the repo and reverted back to 5.1.1, then started applying patches. Here is the 5.1.1 fork:
https://github.com/cromnix/pamac
I am going to apply some more of the bug fixes later this weekend then will push a 5.1.2 release.

**Comment by ICHx** [comment] 2017-10-15 11:58
I would not say it is garbage, but it is definitely slower to startup.

I currently froze my version to 4.9.1.

My PC is quite crappy, it is comprised of i5 670 and GT620.  You may not feel that much.

**Comment by luzpaz** [comment] 2017-11-20 02:34
Yea, "garbage" is harsh. I had resistance to it when it first came out..but now I've actually gotten used to it. So props to the devs...thanks for investing your time on this.

**Comment by luzpaz** [comment] 2018-04-08 21:08
Can this issue be closed ?

**Closed** 2018-04-09 10:53 UTC
